//
//  ViewController.swift
//  TodocPro
//
//  Created by Vasilis Voyiadjis on 18/8/22.
//

import UIKit

class ViewController: UIViewController {

	@IBOutlet weak var withTodosView: UIView!
	@IBOutlet weak var todosCollectionView: UICollectionView!
	var todosRefresherControl: UIRefreshControl!
	@IBOutlet weak var tasksLeftLabel: UILabel!
	
	@IBOutlet weak var removeDoneTodosBarButtonItem: UIBarButtonItem!
	
	@IBOutlet weak var noTodosStackView: UIStackView!
	
	var todos = [Todo]()
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		todosRefresherControl = UIRefreshControl()
		todosRefresherControl.attributedTitle = NSAttributedString(string: "Refreshing todos...")
		todosRefresherControl.addTarget(self, action: #selector(didPullTodoListToRefresh), for: .valueChanged)
		
		todosCollectionView.register(TodoCollectionViewCell.nib(), forCellWithReuseIdentifier: TodoCollectionViewCell.identifier)
		todosCollectionView.delegate = self
		todosCollectionView.dataSource = self
		todosCollectionView.addSubview(todosRefresherControl)
		
		// Configure database and fetch todos
		setupDatabase()
		getAllTodos()
	}
	
	override func viewDidLayoutSubviews() {
		super.viewDidLayoutSubviews()
		todosCollectionView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 50, right: 0)
	}
	
	private func didTodoListUpdated() {
		let totalTodosCount = todos.count
		
		hideNoTodosView(totalTodosCount > 0)
		
		if (totalTodosCount > 0) {
			let doneTodosCount = todos.filter { todo in
				todo.done == true
			}.count
			
			let leftTodosCount = totalTodosCount - doneTodosCount
			
			updateTodoEvents()
			todosCollectionView.reloadData()
			removeDoneTodosBarButtonItem.isEnabled = (doneTodosCount > 0)
			tasksLeftLabel.text = "\(leftTodosCount) task\(leftTodosCount == 1 ? "" : "s") left"
		}
	}
	
	private func updateTodoEvents() {
		todos = todos.map { [weak self] _todo in
			var todo = _todo
			
			todo.onDoneChanged = { [weak self] isDone in
				guard let strongSelf = self else { return }
				
				var updatedTodo = _todo
				updatedTodo.done = isDone
				
				strongSelf.updateTodo(withId: todo.id, newValues: updatedTodo)
				strongSelf.didDoneTodosChanged()
				strongSelf.didTodoListUpdated()
			}
			
			return todo
		}
	}
	
	// Perform haptic feedback when toggling a todo as "done".
	// If all todos are done, perform a haptic feedback that's heavier.
	// I'm having a different function for that and putting in inside didTodoListUpdated(),
	// so it responds as fast as possible and doesn't wait for the list to be refreshed.
	private func didDoneTodosChanged() {
		let totalTodosCount = todos.count
		let doneTodosCount = todos.filter { todo in
			todo.done == true
		}.count
		let leftTodosCount = totalTodosCount - doneTodosCount
		
		let impactFeedbackGenerator = UIImpactFeedbackGenerator(style: leftTodosCount > 0 ? .light : .heavy)
		impactFeedbackGenerator.prepare()
		impactFeedbackGenerator.impactOccurred()
	}
	
	private func hideNoTodosView(_ hide: Bool) {
		noTodosStackView.isHidden = hide
		withTodosView.isHidden = !hide
	}
	
	@objc private func didPullTodoListToRefresh() {
		getAllTodos()
		todosRefresherControl.endRefreshing()
	}
	
	@IBAction private func didTapAddTodoButton(_ sender: Any) {
		let alert = UIAlertController(title: "Add Todo", message: "Enter a brief description of the todo.", preferredStyle: .alert)

		alert.addTextField { textField in
			textField.placeholder = "Todo"
			textField.autocorrectionType = .yes
			textField.autocapitalizationType = .sentences
		}
		
		alert.addAction(UIAlertAction(title: "Cancel", style: .cancel))
		alert.addAction(UIAlertAction(title: "Add", style: .default, handler: { [weak alert, weak self] (_) in
			let todoTextField = alert!.textFields![0]
			let todoText = todoTextField.text!
			if (todoText.isEmpty) {
				return
			}
			
			// id is going to be generated by the database
			let newTodo = Todo(id: -1, shortText: todoText, done: false)
			self?.addTodo(withModel: newTodo)
			self?.didTodoListUpdated()
		}))
		
		self.present(alert, animated: true)
	}
	
	@IBAction func didTapRemoveDoneTodosButton(_ sender: Any) {
		let alert = UIAlertController(title: "Remove Done Todos.", message: "Are you sure you want to remove all todos marked as done?", preferredStyle: .actionSheet)
		
		alert.addAction(UIAlertAction(title: "Cancel", style: .cancel))
		alert.addAction(UIAlertAction(title: "Remove All Done", style: .destructive, handler: { [weak self] (_) in
			guard let strongSelf = self else { return }
			
			let doneTodos = strongSelf.todos.filter { _todo in _todo.done == true }
			for todo in doneTodos {
				strongSelf.removeTodo(withId: todo.id)
			}
			
			strongSelf.didTodoListUpdated()
		}))
		
		self.present(alert, animated: true)
	}
	
	@IBAction private func didTapInfoButton(_ sender: Any) {
		self.performSegue(withIdentifier: "AboutTodocSegue", sender: self)
	}
	
	private func didTapRemoveTodoButton(forTodoAtIndex index: Int) {
		self.removeTodo(withId: self.todos[index].id)
		didTodoListUpdated()
	}
}

// Database
extension ViewController {
	private func setupDatabase() {
		let database = SQLiteDatabase.sharedInstance
		database.createTables()
	}
	
	private func getAllTodos() {
		let fetchedTodos = SQLiteCommands.getAllTodos()
		if (fetchedTodos == nil) {
			showError(withTitle: "Task Failed", message: "Todoc encountered an error trying to fetch todos.")
			return
		}
		
		todos = fetchedTodos!
		didTodoListUpdated()
	}
	
	private func addTodo(withModel todo: Todo) {
		let newTodo = SQLiteCommands.createTodo(withTodoModel: todo)
		if (newTodo == nil) {
			showError(withTitle: "Task Failed", message: "Todoc encountered an error trying to create a todo.")
			return
		}
		
		todos.append(newTodo!)
	}
	
	private func removeTodo(withId todoId: Int64) {
		let removedTodo = SQLiteCommands.removeTodo(withId: todoId)
		if (removedTodo == nil || removedTodo == false) {
			showError(withTitle: "Task Failed", message: "Todoc encountered an error trying to remove a todo.")
			return
		}
		
		todos.removeAll { todo in todo.id == todoId }
	}
	
	private func updateTodo(withId todoId: Int64, newValues: Todo) {
		let updatedTodo = SQLiteCommands.updateTodo(withId: todoId, newTodoValues: newValues)
		if (updatedTodo == nil) {
			showError(withTitle: "Task Failed", message: "Todoc encountered an error trying to update a todo's state.")
			return
		}
		
		let todoIndex = todos.firstIndex { todo in todo.id == todoId }
		if (todoIndex == nil) {
		   print("Todo with id: \(todoId) not found in todos")
		   return
		}
		
		todos[todoIndex!] = updatedTodo!
	}
}

extension ViewController: UICollectionViewDelegate {
	func collectionView(_ collectionView: UICollectionView, contextMenuConfigurationForItemAt indexPath: IndexPath, point: CGPoint) -> UIContextMenuConfiguration? {
		return UIContextMenuConfiguration(identifier: nil, previewProvider: nil) { [weak self] (action) -> UIMenu in
			let index = indexPath.item
			
			let deleteAction = UIAction(
				title: "Delete",
				image: .init(systemName: "trash"),
				identifier: nil,
				discoverabilityTitle: nil,
				attributes: .destructive,
				state: .off
			) { [weak self] _ in
				self?.didTapRemoveTodoButton(forTodoAtIndex: index)
			}
			
			return UIMenu(
				title: "What do you want to do with this todo?",
				image: nil,
				identifier: nil,
				options: .displayInline,
				children: [deleteAction]
			)
		}
	}
}

extension ViewController: UICollectionViewDataSource {
	func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
		return todos.count
	}
	
	func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
		let index = indexPath.item
		let cell = collectionView.dequeueReusableCell(withReuseIdentifier: TodoCollectionViewCell.identifier, for: indexPath) as! TodoCollectionViewCell
		
		cell.configure(withTodo: todos[index])
		
		return cell
	}
	
	func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
		return CGSize(width: collectionView.frame.width, height: 50)
	}
}

extension ViewController: UICollectionViewDelegateFlowLayout {}
