//
//  ViewController.swift
//  TodocPro
//
//  Created by Vasilis Voyiadjis on 18/8/22.
//

import UIKit

class ViewController: UIViewController {

	@IBOutlet var todosCollectionView: UICollectionView!
	@IBOutlet weak var noTodosStackView: UIStackView!
	var todosRefresherControl: UIRefreshControl!
	
	var todos = [Todo]()
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		todosRefresherControl = UIRefreshControl()
		todosRefresherControl.attributedTitle = NSAttributedString(string: "Refreshing todos...")
		todosRefresherControl.addTarget(self, action: #selector(didPullTodoListToRefresh), for: .valueChanged)
		
		todosCollectionView.register(TodoCollectionViewCell.nib(), forCellWithReuseIdentifier: TodoCollectionViewCell.identifier)
		todosCollectionView.delegate = self
		todosCollectionView.dataSource = self
		todosCollectionView.addSubview(todosRefresherControl)
		
		// Configure database and fetch todos
		setupDatabase()
		getAllTodos()
	}
	
	private func didTodoListUpdated() {
		hideNoTodosView(todos.count > 0)
		todosCollectionView.reloadData()
	}
	
	private func hideNoTodosView(_ hide: Bool) {
		noTodosStackView.isHidden = hide
		todosCollectionView.isHidden = !hide
	}
	
	@objc private func didPullTodoListToRefresh() {
		getAllTodos()
		todosRefresherControl.endRefreshing()
	}
	
	@IBAction private func didTapAddTodoButton(_ sender: Any) {
		let alert = UIAlertController(title: "Add Todo", message: "Enter a brief description of the todo.", preferredStyle: .alert)

		alert.addTextField { textField in
			textField.placeholder = "Todo"
			textField.autocorrectionType = .yes
			textField.autocapitalizationType = .sentences
		}
		
		alert.addAction(UIAlertAction(title: "Cancel", style: .cancel))
		alert.addAction(UIAlertAction(title: "Add", style: .default, handler: { [weak alert] (_) in
			let todoTextField = alert!.textFields![0]
			let todoText = todoTextField.text!
			if (todoText.isEmpty) {
				return
			}
			
			// id is going to be generated by the database
			let newTodo = Todo(id: -1, shortText: todoText)
			self.addTodo(withModel: newTodo)
		}))
		
		self.present(alert, animated: true)
	}
	
	@IBAction private func didTapInfoButton(_ sender: Any) {
		self.performSegue(withIdentifier: "AboutTodocSegue", sender: self)
	}
	
	private func didTapRemoveTodoButton(forTodoAtIndex index: Int) {
		let alert = UIAlertController(title: "Delete \"\(todos[index].shortText)\" todo?", message: "Are you sure you want to delete this todo? After tapping \"Delete\" there is no comeback.", preferredStyle: .actionSheet)
		
		alert.addAction(UIAlertAction(title: "Cancel", style: .cancel))
		alert.addAction(UIAlertAction(title: "Delete", style: .destructive, handler: { [weak self] _ in
			self!.removeTodo(withId: self!.todos[index].id)
		}))
		
		self.present(alert, animated: true)
	}
}

// Database
extension ViewController {
	private func setupDatabase() {
		let database = SQLiteDatabase.sharedInstance
		database.createTables()
	}
	
	private func getAllTodos() {
		let fetchedTodos = SQLiteCommands.getAllTodos()
		if (fetchedTodos == nil) {
			return
		}
		
		todos = fetchedTodos!
		didTodoListUpdated()
	}
	
	private func addTodo(withModel todo: Todo) {
		let newTodo = SQLiteCommands.createTodo(withTodoModel: todo)
		if (newTodo == nil) {
			return
		}
		
		todos.append(newTodo!)
		didTodoListUpdated()
	}
	
	private func removeTodo(withId todoId: Int64) {
		let removedTodo = SQLiteCommands.removeTodo(withId: todoId)
		if (removedTodo == nil || removedTodo == false) {
			return
		}
		
		todos.removeAll { todo in todo.id == todoId }
		didTodoListUpdated()
	}
}

extension ViewController: UICollectionViewDelegate {
	func collectionView(_ collectionView: UICollectionView, contextMenuConfigurationForItemAt indexPath: IndexPath, point: CGPoint) -> UIContextMenuConfiguration? {
		return UIContextMenuConfiguration(identifier: nil, previewProvider: nil) { [weak self] (action) -> UIMenu in
			let index = indexPath.item
			
			let deleteAction = UIAction(
				title: "Delete",
				image: .init(systemName: "trash"),
				identifier: nil,
				discoverabilityTitle: nil,
				attributes: .destructive,
				state: .off
			) { [weak self] _ in
				self?.didTapRemoveTodoButton(forTodoAtIndex: index)
			}
			
			return UIMenu(
				title: "What do you want to do with this Todo?",
				image: nil,
				identifier: nil,
				options: .displayInline,
				children: [deleteAction]
			)
		}
	}
}

extension ViewController: UICollectionViewDataSource {
	func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
		return todos.count
	}
	
	func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
		let index = indexPath.item
		let cell = collectionView.dequeueReusableCell(withReuseIdentifier: TodoCollectionViewCell.identifier, for: indexPath) as! TodoCollectionViewCell
		
		cell.configure(withTodo: todos[index])
		
		return cell
	}
	
	func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
		return CGSize(width: collectionView.frame.width, height: 50)
	}
}

extension ViewController: UICollectionViewDelegateFlowLayout {}
